default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  port: <%= ENV.fetch('POSTGRES_PORT') %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'weather_lookup_development' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'weather_lookup_test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'weather_lookup_production' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
